//
// Created by 孙全 on 2022/5/20.
//
#pragma once
#ifndef OPENGL_ASSIGNTYPE_H
#define OPENGL_ASSIGNTYPE_H

#endif //OPENGL_ASSIGNTYPE_H

#define ASSIGN_LEARN_OPENGL_TRIANGLE_SIMPLE 1001
#define ASSIGN_LEARN_OPENGL_TRIANGLE_SIMPLE_VBO 1002
