//
// Created by 孙全 on 2022/5/20.
//
#pragma once
#ifndef OPENGL_ASSIGNTYPE_H
#define OPENGL_ASSIGNTYPE_H

#endif //OPENGL_ASSIGNTYPE_H

//triangle
#define ASSIGN_LEARN_OPENGL_TRIANGLE_SIMPLE 1001
#define ASSIGN_LEARN_OPENGL_TRIANGLE_SIMPLE_VBO 1002
#define ASSIGN_LEARN_OPENGL_TRIANGLE_SIMPLE_VAO 1003
#define ASSIGN_LEARN_OPENGL_RECT 1004
#define ASSIGN_LEARN_OPENGL_RECT_TWO_FRAGMENT_SHADER 1005
#define ASSIGN_LEARN_OPENGL_RECT_EBO 1006

//shaders
#define ASSIGN_LEARN_OPENGL_SHADER_SIMPLE_SHADER 2001



